#!/bin/sh
# gen-sources.sh
#
# Writes SOURCES.md from build.json.
#
# Generated rather than hand-written for one reason: a corresponding-source
# notice that disagrees with what was actually published is worse than none at
# all. Every URL, digest, version and commit below is read out of the same
# build.json the build scripts fetch from, so the notice cannot drift from the
# artifacts. CI regenerates it and diffs, so a pin bumped without regenerating
# fails the build rather than shipping a stale claim.
#
# Three licence situations, and no single mechanism covers all three:
#
#   make, bash    GPLv3+, built here from unmodified pinned tarballs by scripts
#                 in this repository. GPLv3 §6(d) allows offering the
#                 corresponding source from a network location, which is what
#                 the recorded upstream URL and digest are.
#
#   busybox       GPLv2-only. v2 has no §6(d): there is no provision for
#                 satisfying the offer by pointing somewhere else. So the
#                 source tarball is published in the same release as the
#                 binary, and mirror.sh fetches and republishes it.
#
#   devkitARM     GPLv3+, but not our build and not upstream GNU's sources.
#                 devkitPro ships patched GCC, binutils and newlib; the
#                 corresponding source is therefore devkitPro's tree at the
#                 tag their release was cut from, not ftp.gnu.org's release of
#                 the same version number. Nothing in this repository builds
#                 it, so §6(d) points at their buildscripts repository.
#
# Usage:
#   gen-sources.sh            write <repo>/SOURCES.md
#   gen-sources.sh -          write to stdout (CI diffs this against the file)
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)

BUILD_JSON="${BUILD_JSON:-$ROOT/build.json}"
export BUILD_JSON
. "$SCRIPT_DIR/lib.sh"

need jq

DEST="${1:-$ROOT/SOURCES.md}"

# Every value comes through cfg, so a missing pin fails loudly here rather than
# leaving a blank cell in a licence notice.
MAKE_V=$(cfg '.posix.make.version')
MAKE_U=$(cfg '.posix.make.url')
MAKE_S=$(cfg '.posix.make.sha256')
MAKE_L=$(cfg '.posix.make.licence')

BASH_V=$(cfg '.posix.bash.version')
BASH_U=$(cfg '.posix.bash.url')
BASH_S=$(cfg '.posix.bash.sha256')
BASH_L=$(cfg '.posix.bash.licence')

BB_V=$(cfg '.mirrors.busybox.version')
BB_U=$(cfg '.mirrors.busybox.url')
BB_S=$(cfg '.mirrors.busybox.sha256')
BB_SU=$(cfg '.mirrors.busybox.source_url')
BB_SS=$(cfg '.mirrors.busybox.source_sha256')
BB_L=$(cfg '.mirrors.busybox.licence')

DKA_V=$(cfg '.mirrors.devkitarm.version')
DKA_L=$(cfg '.mirrors.devkitarm.licence')
DKA_TAG=$(cfg '.mirrors.devkitarm.buildscripts_tag')
DKA_COMMIT=$(cfg '.mirrors.devkitarm.buildscripts_commit')

emit() {
  cat <<EOF
# Sources and corresponding source offers

<!-- Generated by scripts/gen-sources.sh from build.json. Do not edit by hand:
     CI regenerates this file and fails if it differs, because a
     corresponding-source notice that disagrees with what was published is
     worse than no notice at all. -->

RotomLab downloads prebuilt binaries so that its users need no development
environment. Several of those binaries are under the GNU GPL, which obliges
whoever distributes them to make the corresponding source available. This file
records, for every component published from this repository, what it is, where
it came from, its SHA-256, and how its corresponding source is provided.

Everything here is fetched by digest. \`build.json\` pins every input and
\`scripts/lib.sh\` verifies each download against its pin before anything uses
it, so the digests below are not a description of what was fetched — they are
the condition under which it was accepted.

## The three cases

The GPL does not offer one mechanism that fits all three of these, so they are
handled differently and it is worth being explicit about which is which.

| | Licence | Who built it | How corresponding source is provided |
|---|---|---|---|
| \`make\`, \`bash\` | GPLv3-or-later | Us, from unmodified upstream tarballs | GPLv3 §6(d): the pinned upstream URL below, plus the build scripts in this repository |
| \`busybox\` | **GPLv2-only** | Upstream (official static build), mirrored | The source tarball is **published alongside the binary** in the same release |
| \`devkitARM\` | GPLv3-or-later | **devkitPro**, from patched GCC/binutils/newlib | devkitPro's \`buildscripts\` at the tag their release was cut from |

busybox is the case that catches people out. GPLv2 §3 lets a distributor
accompany a binary with source, with a written offer, or — for noncommercial
distribution — by passing on an offer received. It has no equivalent of GPLv3
§6(d), which is the clause that permits merely telling recipients where to
download the source. Linking to busybox.net is therefore not a way to comply
with v2, and the source tarball travels with the binary instead.

devkitARM is the case that is easy to get subtly wrong. It contains GCC,
binutils and newlib, so the reflex is to point at ftp.gnu.org. That would be
the wrong source: devkitPro patches these and builds them with their own
recipes, and the corresponding source for *their* binary is *their* tree, not
the upstream release that shares its version number. Nothing in this repository
compiles devkitARM — it is fetched as five prebuilt pacman packages and
repackaged — so we have no build recipe of our own to offer either.

## Built here

Built inside \`alpine:3.22\` against musl and statically linked, by
\`scripts/build-posix.sh\`, from the tarballs below. Unmodified: nothing is
patched, and the configure flags are in that script with the reasoning for
each.

### GNU Make $MAKE_V

- Licence: \`$MAKE_L\`
- Source: <$MAKE_U>
- SHA-256: \`$MAKE_S\`
- Build recipe: \`scripts/build-posix.sh\` in this repository
- Published as: \`make-$MAKE_V-linux-amd64\`

### GNU Bash $BASH_V

- Licence: \`$BASH_L\`
- Source: <$BASH_U>
- SHA-256: \`$BASH_S\`
- Build recipe: \`scripts/build-posix.sh\` in this repository
- Published as: \`bash-$BASH_V-linux-amd64\`

## Mirrored

### busybox $BB_V

Upstream's own official static build, republished byte-for-byte; we do not
compile it. GPLv2-only, so the source accompanies the binary.

- Licence: \`$BB_L\`
- Binary: <$BB_U>
  - SHA-256: \`$BB_S\`
  - Published as: \`busybox-$BB_V-linux-amd64\`
- **Corresponding source**: <$BB_SU>
  - SHA-256: \`$BB_SS\`
  - **Published as \`busybox-$BB_V.tar.bz2\` in the same release as the binary**

### devkitARM $DKA_V

devkitPro's ARM toolchain. \`devkitARM\` is a metapackage with no files of its
own, so what is mirrored is its dependency closure: the packages below are
fetched, their pacman metadata dropped, their trees merged, and the result
repackaged as one \`.tar.xz\` with the \`opt/devkitpro/devkitARM\` prefix intact.
No file's contents are altered.

- Licence: \`$DKA_L\` (GCC, binutils and newlib, as patched by devkitPro)
- **Corresponding source**: <https://github.com/devkitPro/buildscripts> at tag
  [\`$DKA_TAG\`](https://github.com/devkitPro/buildscripts/tree/$DKA_TAG),
  commit
  [\`$DKA_COMMIT\`](https://github.com/devkitPro/buildscripts/tree/$DKA_COMMIT)
  — devkitPro's patches and build recipes, which is what these binaries were
  actually built from. The upstream GNU releases of the same version numbers
  are **not** the corresponding source for them.

  The commit is recorded as well as the tag because a tag can be moved, and an
  offer that points at a moving target is not an offer. The link is to
  \`/tree/\` rather than \`/releases/tag/\`: devkitPro publishes the tag but no
  GitHub release for it, so the release URL would 404.
- Published as: \`devkitarm-$DKA_V-linux-amd64.tar.xz\`

Packages mirrored:

| Package | Version | SHA-256 |
|---|---|---|
$(jq -r '.mirrors.devkitarm.packages[]
         | "| [`\(.name)`](\(.url)) | `\(.version)` | `\(.sha256)` |"' "$BUILD_JSON")

## Decomp host tools

Each \`<game>-hosttools-*.tar.xz\` holds the build tools a pret decompilation
project ships in its own \`tools/\` directory — \`preproc\`, \`gbagfx\`, \`scaninc\`
and the rest — compiled by \`scripts/build-host-tools.sh\` from the repository
and commit below, with no modification to their sources. The corresponding
source is that repository at that commit.

The pret projects publish no repository-level licence file, and individual
tools carry their own terms in their own headers. This file does not restate
terms it cannot verify; consult the repository at the pinned commit.

| Decomp | Commit | Games |
|---|---|---|
$(jq -r '.decomps | to_entries[]
         | "| [`\(.key)`](\(.value.repo)) | [`\(.value.commit)`](\(.value.repo)/tree/\(.value.commit)) | \(.value.games | join(", ")) |"' "$BUILD_JSON")

## Build environment

Every binary built here is produced inside \`alpine:3.22\` and statically linked
against musl, so it runs on any Linux distribution regardless of its glibc
version.

\`Containerfile\` is that image, and it is not a description of one:
\`.github/workflows/release.yml\` builds it and runs the whole pipeline inside
it, so the container recorded here is the one the published binaries came out
of. Reproducing a release means building that file and running the same
scripts.

The per-artifact workflows — \`host-tools.yml\`, \`posix.yml\`, \`mirror.yml\`,
\`fragment.yml\` — start from the same \`alpine:3.22\` base but install only the
packages each one needs, so editing a decomp pin does not rebuild bash. They
are the fast feedback path, not the release path, and this file describes the
release path.

## Reproducing any of this

\`build.json\` pins every input by URL and SHA-256, and \`scripts/\` contains
exactly what CI runs — there is no hidden state and no unpinned fetch. Running
\`scripts/build-posix.sh\` or \`scripts/mirror.sh\` in the container reproduces
the corresponding artifacts.
EOF
}

if [ "$DEST" = - ]; then
  emit
else
  emit >"$DEST"
  log "wrote $DEST"
fi
